workspace/config/routes.rb
Rails.application.routes.draw do
  get 'testdatum/index'

  get 'testdatum/import'
  
  resources :testdatum do 
    collection { post :import}
  end
  root to: "testdatum#index"

end

workspace/app/models/testdatum.rb
class Testdatum < ActiveRecord::Base
    require 'csv'
    def self.import(file)
        CSV.foreach(file.path, headers: true) do |row|
            Testdatum.create! row.to_hash
        end
    end
    
    # def self.import(file)
    #     CSV.foreach(file.path, headers:true, header_converters: symbol) do |row|
    #         Stuff.create! row.to_hash
    #     end
    # end
    
#   include Mongoid::Document
#   include Mongoid::Timestamps

#   def self.import!(file)
#     columns = []
#     instances = []
#     CSV.foreach(file.path) do |row|
#       if columns.empty?
#         # We dont want attributes with whitespaces
#         columns = row.collect { |c| c.downcase.gsub(' ', '_') }
#         next
#       end

#       instances << create!(build_attributes(row, columns))
#     end
#     instances
#   end

#   private

#   def self.build_attributes(row, columns)
#     attrs = {}
#     columns.each_with_index do |column, index|
#       attrs[column] = row[index]
#     end
#     attrs
#   end

end

workspace/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

workspace/app/controllers/testdatum_controller.rb
class TestdatumController < ApplicationController
  def index
    @testdatum = Testdatum.all
  end

  def import
    Testdatum.import(params[:file])
    redirect_to root_url, notice: "Activity Data imported!" 
  end
end

workspace/app/helpers/application_helper.rb
module ApplicationHelper
end

workspace/app/helpers/testdatum_helper.rb
module TestdatumHelper
end

workspace/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

workspace/app/views/testdatum/import.html.erb
<h1>Testdatum#import</h1>
<p>Find me in app/views/testdatum/import.html.erb</p>

workspace/app/views/testdatum/index.html.erb
<%= flash[:notice] %>
<table>
    <thread>
        <tr>
            <th>Date</th>
            <th>Time</th>
            <th>Var_1</th>
            <th>Var_2</th>
            <th>Var_3</th>
            <th>Var_4</th>
            <th>Var_5</th>
            <th>Var_6</th>
            <th>Var_7</th>
            <th>Var_8</th>
        </tr>
    </thread>
    <tbody>
        <% @testdatum.each do |testdatum| %>
        <tr>
            <th>testdatum.date</th>
            <th>testdatum.time</th>
            <th>testdatum.var1</th>
            <th>testdatum.var2</th>
            <th>testdatum.var3</th>
            <th>testdatum.var4</th>
            <th>testdatum.Var5</th>
            <th>testdatum.var6</th>
            <th>testdatum.var7</th>
            <th>testdatum.var8</th>
        </tr>
        <% end %>
    </tbody>
</table>

<div>
    <h4>Import</h4>
    <%= form_tag testdatum_import_path, multipart: true do %>
        <%= file_field_tag :file %>
        <%= submit_tag "Import CSV" %>
    <% end %>
    
</div>